language: node_js
node_js:
  - "12.16.1"

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master

notifications:
  email:
    recipients:
    - andreluiz.onete@hotmail.com
    on_success: change
    on_failure: always
